### ISSUE TITLE
[Bug] Filters and Actions not rendered to documentation site

### ISSUE THREAD

**Issue by nicolasgalvez** [timber/teak#5]
### Expected Behavior

There should be content in on the documentation website for actions and filters.

### Actual behavior

On the documentation website the following pages have no content aside from the title:
https://timber.github.io/docs/v2/hooks/actions/
and https://timber.github.io/docs/v2/hooks/filters/

### Steps to reproduce behavior

1. Go to the website 
2. Click on Actions or Filters in the sidebar
3. There is a blank page for both
...

### Notes

I have skimmed the contributing guide and see something about automatically rendering documentation for actions and filters. I guess this isn't working for some reason.

### What version of Timber are you using?

Timber 2

### What version of WordPress are you using?

WordPress 6.5

### What version of PHP are you using?

PHP 8.1

### How did you install Timber?

None

**Comment by nick-project6** [comment]
Wow thanks for the quick fix! I really appreciate it!

**Comment by nicolasgalvez** [comment]
Thanks for the quick fix! I really appreciate it.
